routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [
    'uses' => 'HomeController@index',
    'as'   => 'home'
]);

Route::get('/home', function () {
    return redirect()->route('home');
});

/**
 * Vacaciones
 */
Route::post('vacaciones/store', 'VacacionesController@store')->name('vacaciones.store');
Route::post('vacaciones/storeb', 'VacacionesController@storeb')->name('vacaciones.storeb');

Route::get('vacaciones', 'VacacionesController@index')->name('vacaciones.index');
Route::get('vacacionesdt', 'VacacionesController@getVacaciones');
Route::get('vacaciones/user/{id}', 'HomeController@getVacacionesPorUsuario')->name('vacaciones.foruser');
Route::get('vacaciones/users', 'HomeController@getAllVacaciones')->name('vacaciones.foralluser');
Route::post('vacaciones/approve/{id}', 'VacacionesController@approveVacaciones')->name('vacaciones.approve');
Route::post('vacaciones/deny/{id}', 'VacacionesController@denyVacaciones')->name('vacaciones.deny');
Route::post('vacacionesdtall', 'VacacionesController@getVacacionesAllDt');
Route::post('vacacionesdtdeny', 'VacacionesController@getVacacionesDenyDt');
Route::post('vacacionesdtapprove', 'VacacionesController@getVacacionesApproveDt');
Route::post('vacacionesdtnotapprove', 'VacacionesController@getVacacionesNotApproveDt');
Route::delete('/vacaciones/{id}', 'VacacionesController@destroy');
Route::post('/vacacionesforuseryear', 'VacacionesController@getVacacionesForUser');


/**
 * Viajes
 */
Route::get('viajes', 'ViajesController@index')->name('viajes.index');
Route::get('viajes/create', 'ViajesController@create')->name('viajes.create');
Route::get('viajes/{id}', 'ViajesController@show')->name('viajes.show');
Route::post('viajes/store', 'ViajesController@store')->name('viajes.store');
Route::get('viajesdt', 'ViajesController@getViajes');
Route::post('viajes/approve/{id}', 'ViajesController@approveViaje')->name('vacaciones.approve');
Route::post('viajes/deny/{id}', 'ViajesController@denyViaje')->name('vacaciones.deny');
Route::get('viajesdtall', 'ViajesController@getViajesAllDt');
Route::get('viajesdtdeny', 'ViajesController@getViajesDenyDt');
Route::get('viajesdtapprove', 'ViajesController@getViajesApproveDt');
Route::get('viajesdtnotapprove', 'ViajesController@getViajesNotApproveDt');
/**
 * Nominas
 */
Route::get('nominas', 'NominasController@index')->name('nominas.index');

/**
 * Documentacion
 */
Route::get('documentacion', 'DocumentacionController@index')->name('documentacion.index');
Route::get('documentacion/create', 'DocumentacionController@create')->name('documentacion.create');
Route::post('documentacion/store', 'DocumentacionController@store')->name('documentacion.store');
Route::get('documentacion/{id}/edit', 'DocumentacionController@edit')->name('documentacion.edit');
Route::put('documentacion/{id}/update', 'DocumentacionController@update')->name('documentacion.update');
Route::get('documentacion/descargar/{id}', 'DocumentacionController@download')->name('documentacion.download');
Route::delete('documentacion/destroy/{id}', 'DocumentacionController@destroy')->name('documentacion.destroy');

/**
 * Beneficios
 */
Route::get('/beneficios', 'BeneficiosController@index')->name('beneficios.index');
Route::get('/beneficios/create', 'BeneficiosController@create')->name('beneficios.create');
Route::post('/beneficios/store', 'BeneficiosController@store')->name('beneficios.store');
Route::put('/beneficios/{id}/update', 'BeneficiosController@update')->name('beneficios.update');
Route::delete('/beneficios/{id}', 'BeneficiosController@delete')->name('beneficios.delete');
Route::get('/usersj', 'BeneficiosController@usersj');

/**
 * Usuarios
 */
Route::get('/usuarios', 'UserController@index')->name('users.index');
Route::get('/usuarios/create', 'UserController@create')->name('users.create');
Route::post('/usuarios/store', 'UserController@store')->name('users.store');
Route::get('/usuarios/{user}/edit', 'UserController@edit')->name('users.edit');
Route::put('/usuarios/{user}', 'UserController@update')->name('users.update');

app/User.php
<?php

namespace App;

use Spatie\Permission\Traits\HasRoles;
use Carbon\Carbon;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    protected $guard_name = 'web';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    public function vacaciones()
    {
        return $this->hasMany(Vacaciones::class);
    }

    public function beneficios()
    {
        return $this->belongsToMany('App\Beneficio');
    }
    public function scopeNominas($query)
    {
        $now = new Carbon();
        return $this->documentacion()->where('file_type', '=', 'nomina')->whereYear('created_at','=',$now->year);
    }

    public function documentacion()
    {
        return $this->hasMany(Documentacion::class);
    }

    public function hasFiscalDocs()
    {
        return $this->documentacion()
            ->where('date', '>=', date('Y'))
            ->where('file_type', '=', 'mod145')
            ->orWhere('file_type', '=', 'irpf')
            ->count() > 0;
    }

    public function hasIrpf()
    {
        return $this->documentacion()
            ->where('date', '>=', date('Y'))
            ->where('file_type', '=', 'irpf')
            ->count() > 0;
    }

    public function hasMod145()
    {
        return $this->documentacion()
            ->where('date', '>=', date('Y'))
            ->where('file_type', '=', 'mod145')
            ->count() > 0;
    }

    public function getLastIrpfAttribute()
    {
        return $this->documentacion()
            ->where('date', '>=', date('Y'))
            ->where('file_type', '=', 'irpf')
            ->orderBy('date', 'DESC')
            ->first();
    }

    public function getLastMod145Attribute()
    {
        return $this->documentacion()
            ->where('date', '>=', date('Y'))
            ->where('file_type', '=', 'mod145')
            ->orderBy('date', 'DESC')
            ->first();
    }

    public function viajes()
    {
        return $this->hasMany(Viajes::class);
    }
}

resources/views/home.blade.php
@extends('layouts.app')
@section('content')
    <div class="page">
        <div class="page-content container-fluid">
            <div class="row">
                <div class="col-sm-6 col-md-3">
                    <div class="panel panel-bordered panel-h350">
                        <div class="panel-body">
                            <div class="card-block" align="center">
                                <a class="avatar avatar-lg" href="javascript:void(0)">
                                    <img src="{{asset('global/5.jpg')}}" alt="...">
                                </a>
                                <h4 class="profile-user">{{auth()->user()->name}}</h4>
                                <p class="profile-job">{{auth()->user()->roles()->first()->name}}</p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="clearfix"></div>
                <div class="col-sm-6 col-md-3">
                    <div class="panel panel-bordered panel-h350">
                        <div class="panel-body">
                            <h5>TUS NOMINAS</h5>
                            <ul class="list-group list-nominas">
                                @foreach (auth()->user()->nominas()->take(5)->get() as $nomina)
                                    <li class="list-group-item pl-0 pr-0 pb-3 text-uppercase">
                                        <a href="{{ route('documentacion.download', $nomina->id) }}">
                                            <i class="fa fa-fw fa-file-o" aria-hidden="true"></i> {{ $nomina->title }}
                                        </a>
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                        <div class="panel-footer">
                            <a href="{{ route('nominas.index') }}" style="color: darkgray !important;">
                                Ver más nóminas...
                            </a>
                        </div>
                    </div>
                </div>

                <div class="clearfix"></div>


                <div class="col-sm-6 col-md-3">
                    <div class="col p0">
                        <div class="panel panel-bordered panel-beneficios panel-h350">
                            <div class="panel-body">
                                <h4 align="center">BENEFICIOS SOCIALES </h4>
                                @if(!is_null(Auth::User()->beneficios()->get()))
                                    <div style="max-height: 240px;overflow-y: scroll;">
                                        @foreach(Auth::User()->beneficios()->get() as $beneficio)
                                            <div class="list-group-item  ui-draggable ui-draggable-handle"
                                                 data-title="Meeting" data-stick="true" data-color="red-600"
                                                 style="padding: 0px;">
                                                <i
                                                        class="wb-medium-point white-600 mr-10"
                                                        aria-hidden="true"></i>{{$beneficio->titulo}}

                                            </div>
                                        @endforeach
                                        @endif
                                    </div>
                                    <div class="center-block text-center" align="center">
                                        <a href="{{route('beneficios.index')}}">Ver todos los beneficios</a>
                                    </div>
                            </div>

                        </div>
                    </div>
                </div>

                @if(auth()->user()->hasFiscalDocs())
                    <div class="col-sm-6 col-md-3">

                        <div class="col p0">
                            <div class="panel panel-bordered panel-documentos panel-h350">
                                <div class="panel-body">
                                    <h4>DOCUMENTOS FISCALES 2017</h4>
                                    @if(auth()->user()->hasIrpf())
                                        <h1 class="m0" style="margin-top:-10px;">
                                            <a class="irpf"
                                               href="{{ route('documentacion.download', auth()->user()->last_irpf->id) }}">
                                                IRPF
                                            </a>
                                        </h1>
                                    @endif
                                    @if(auth()->user()->hasMod145())
                                        <h1 class="m0" style="margin-top:-10px;">
                                            <a class="mod145"
                                               href="{{ route('documentacion.download', auth()->user()->last_mod145->id) }}">
                                                MODELO 145
                                            </a>
                                        </h1>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                @endif

                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-bordered">
                            <div class="panel-body">
                                <div class="calendar-container">
                                    <div class="col-md-3 col-sm-2">
                                        <section class="page-aside-section">
                                            <h4 class="m0">CALENDARIOS</h4>
                                            <h5 class="m0 text-uppercase">Vacaciones y cumpleaños</h5>
                                            <div class="list-group calendar-list">
                                                @if(!is_null($users))

                                                    <a class="list-group-item calendar-event"
                                                       data-title="Meeting"
                                                       data-stick=true data-color="red-600"
                                                       href="{{route('vacaciones.foralluser')}}">
                                                        <i class="wb-medium-point red-600 mr-10"
                                                           aria-hidden="true"></i>Ver
                                                        todos los usuarios

                                                    </a>
                                                    @foreach($users as $user)
                                                        <a class="list-group-item calendar-event"
                                                           data-title="Meeting"
                                                           data-stick=true data-color="red-600"
                                                           href="{{route('vacaciones.foruser',$user->id)}}">
                                                            <i class="wb-medium-point red-600 mr-10"
                                                               aria-hidden="true"></i>{{$user->name}}
                                                        </a> @endforeach
                                                @endif
                                            </div>
                                        </section>
                                    </div>
                                    <div class="col-md-9">
                                        <div class="calendar-container">
                                            {!! $calendar->calendar() !!}
                                            <div class="modal fade" id="addNewCalendar" aria-hidden="true"
                                                 aria-labelledby="addNewCalendar" role="dialog" tabindex="-1">
                                                <div class="modal-dialog modal-simple">
                                                    <form class="modal-content form-horizontal" method="post"
                                                          action="{{route('vacaciones.store')}}" role="form">
                                                        <input type="hidden" name="_token"
                                                               value="{{ csrf_token() }}">
                                                        <div class="modal-header">
                                                            <button type="button" class="close"
                                                                    aria-hidden="true"
                                                                    data-dismiss="modal">×
                                                            </button>
                                                            <h4 class="modal-title">Solicitud de vacaciones</h4>
                                                        </div>
                                                        <div class="modal-body">
                                                            <div class="form-group row">
                                                                <label class="col-md-4 form-control-label"
                                                                       for="ename">Periodo
                                                                    de
                                                                    vacaciones:</label>
                                                                <div class="col-md-6">
                                                                    <input type="text"
                                                                           name="periodo_de_vacaciones"
                                                                           class="form-control">
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <div class="form-actions">
                                                                <button class="btn btn-primary" type="submit">
                                                                    Solicitar
                                                                </button>
                                                                <a class="btn btn-sm btn-white"
                                                                   data-dismiss="modal"
                                                                   href="javascript:void(0)">Cancelar</a>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Site Action -->
        <div class="site-action" data-plugin="actionBtn">
            <button type="button" class="site-action-toggle btn-raised btn btn-success btn-floating">
                <i class="front-icon wb-plus animation-scale-up" aria-hidden="true"></i>
                <i class="back-icon wb-trash animation-scale-up" aria-hidden="true"></i>
            </button>
        </div>
        <!-- End Site Action -->
    </div>
@endsection

@push('scripts')
<script src="{{asset('global/js/Plugin/bootstrap-datepicker.js')}}"></script>
<script>
    $(document).ready(function () {

        $('input[name="periodo_de_vacaciones"]').daterangepicker({
            "showDropdowns": true,
            "autoApply": true,
            "locale": {
                "format": "DD/MM/YYYY",
                "separator": " - ",
                "applyLabel": "Apply",
                "cancelLabel": "Cancel",
                "fromLabel": "From",
                "toLabel": "To",
                "customRangeLabel": "Custom",
                "weekLabel": "W",
                "daysOfWeek": [
                    "Dom",
                    "Lun",
                    "Mar",
                    "Mie",
                    "Jue",
                    "Vie",
                    "Sab"
                ],
                "monthNames": [
                    "Enero",
                    "Febrero",
                    "Marzo",
                    "Abril",
                    "Mayo",
                    "Junio",
                    "Julio",
                    "Agosto",
                    "Septiembre",
                    "Octubre",
                    "Noviembre",
                    "Diciembre"
                ],
                "firstDay": 1
            },
            "opens": "center"
        }, function (start, end, label) {
            console.log("New date range selected: ' + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD') + ' (predefined range: ' + label + ')");
        });
    });
</script>
@endpush